# Site wide configuration

title: andrew brooks
locale: en_US
description: data science side projects, thoughts & experiments
logo: ab-logo.jpg
search: true

#url:              http://localhost:4000
url:               http://brooksandrew.github.io/simpleblog


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: andrew brooks
  avatar: bio-photo.jpg
  email: andrewbrooksct@gmail.com
  disqus-shortname: brooksandrewblog
  twitter: #username
  facebook: #username
  github: brooksandrew
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: #username
    analytics: "UA-52978786-2"
    verify:
    ad-client:
    ad-slot: 
  bing-verify:

